steps: 
- name: 'gcr.io/cloud-builders/docker'
  env:
    - '_API_URL=http://localhost:8080'
    - '_TRACKING_ID=1'
  substitutions:
    - _TRACKING_ID: ''
  args: ['build',
          '--build-arg',
          '${_TRACKING_ID}',
          '-f',
          'Dockerfile.prod',
          '-t',
          'gcr.io/$PROJECT_ID/github.com/creatix-frontend:$SHORT_SHA',
         '.']
images:
  - 'gcr.io/$PROJECT_ID/github.com/creatix-frontend:$SHORT_SHA'

