steps: 
- name: 'gcr.io/cloud-builders/docker'
  env:
    - '_API_URL=http://localhost:8080'
    - '_TRACKING_ID=1'
   args: ['build',
          '--build-arg',
          'TRACKING_ID=${_TRACKING_ID}',
          '-f',
          'Dockerfile.prod',
          '-t',
          'gcr.io/$PROJECT_ID/github.com/creatix-frontend:$SHORT_SHA',
         '.']
substitutions:
  - _TRACKING_ID: ''
images:
  - 'gcr.io/$PROJECT_ID/github.com/creatix-frontend:$SHORT_SHA'

