export const SET_ACTIVE_CARD = "SET_CTIVE_CARD"

export const OPEN_MODAL = "OPEN_MODAL"

export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const SHOW_FEEDBACK = "SHOW_FEEDBACK";
export const LOAD_FEEDBACK = "LOAD_FEEDBACK";
export const VOTE_FEEDBACK = "VOTE_FEEDBACK";
