export const SET_ACTIVE_CARD = "SET_CTIVE_CARD";

export const TOGGLE_MODAL = "TOGGLE_MODAL";

export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const SHOW_FEEDBACK = "SHOW_FEEDBACK";
export const FETCH_FEEDBACK = "LOAD_FEEDBACK";
export const VOTE_FEEDBACK = "VOTE_FEEDBACK";

// AUTH
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAILURE = "VERIFY_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// SIGNUP
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// Reset password 
export const RESET_PWD_REQUEST = "RESET_PWD_REQUEST"
export const RESET_PWD_SUCCESS = "RESET_PWD_SUCCESS"
export const RESET_PWD_FAILURE = "RESET_PWD_FAILURE"

//Feedback
export const GET_FEEDBACK_REQUEST = "GET_FEEDBACK_REQUEST";
export const GET_FEEDBACK_SUCCESS = "GET_FEEDBACK_SUCCESS";
export const GET_FEEDBACK_FAILURE = "GET_FEEDBACK_FAILURE";

export const POST_FEEDBACK_REQUEST = "POST_FEEDBACK_REQUEST";
export const POST_FEEDBACK_SUCCESS = "POST_FEEDBACK_SUCCESS";
export const POST_FEEDBACK_FAILURE = "POST_FEEDBACK_FAILURE";


// Clappers
export const CLAP_FEEDBACK_REQUEST = "CLAP_FEEDBACK_REQUEST";
export const CLAP_FEEDBACK_SUCCESS = "CLAP_FEEDBACK_SUCCESS";
export const CLAP_FEEDBACK_FAILURE = "CLAP_FEEDBACK_FAILURE";
